name: Generate Snake Dark

on:
  workflow_dispatch:   # rodar manualmente
  schedule:
    - cron: "0 */12 * * *"  # a cada 12 horas

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gerar a cobrinha dark
      - name: Generate snake dark
        uses: Platane/snk@v3
        with:
          github_user_name: elielguedes
          outputs: dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit e push da cobrinha para a main
      - name: Push to main branch
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update GitHub contribution snake"
          branch: main
          file_pattern: "dist/github-contribution-grid-snake-dark.svg"
